export const DEFAULT_TRANSACTION_PAGE_SIZE = 50;
export const MIN_TRANSACTION_PAGE_SIZE = 1;
export const MAX_TRANSACTION_PAGE_SIZE = 100;
export const TRANSACTION_PAGE_SIZE_OPTIONS = [10, 25, 50, 100];
